# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /code

# Copy the requirements file into the container
COPY ./requirements.txt /code/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy the rest of your application's code
COPY . /code/

# Make port 7860 available to the world outside this container
# Hugging Face Spaces uses this port by default
EXPOSE 7860

# Run recommender.py when the container launches
CMD ["gunicorn", "--bind", "0.0.0.0:7860", "recommender:app"]
